### ISSUE TITLE
Bot stops playing 10-15 seconds before audio stops, but remains in the voice channel

### ISSUE THREAD

**Issue by Taha-Chaudhry** [amishshah/ytdl-core-discord#139] opened 2020-02-07 06:14 UTC
My code: 

      var input = await ytdl(server.queue[0]);
      const pcm = input.pipe(
        new prism.opus.Decoder({ rate: 48000, channels: 2, frameSize: 960 })
      );

      server.dispatcher = connection.playConvertedStream(
        pcm,
        // { passes: 3 },
        { highWaterMark: 1024 * 1024 * 10}
      );

**Comment by LordDamionDevil** [comment] 2020-03-02 16:29
Having same issue but a bit different.
It plays for 1-2 mins and then for some reason the end function gets triggered

**Comment by reisdev** [comment] 2020-03-29 18:46
Same problem here!

My `package.json`:
```json
{
    "dependencies": {
        "@discordjs/opus": "^0.1.0",
        "discord.js": "12.0.2",
        "ffmpeg": "0.0.4",
        "fluent-ffmpeg": "^2.1.2",
        "ytdl-core-discord": "^1.1.0"
    },
    "engine": {
        "node": "12.2.0"
    }
}
```
My code: 

```typescript
ytdl(song.url, { filter: "audioonly", quality: "highestaudio", highWaterMark: 1 << 15 }).then(stream => {
        const dispatcher = queue.connection.play(stream, { type: "opus", highWaterMark: 15 });
        dispatcher.setVolumeLogarithmic(queue.volume);
        dispatcher.on("finish", () => {
            queue.songs.shift();
            playSong(bot, msg, queue.songs[0]);
        })
})
```

I've downgraded the node version to the 10.16 and the problem is gone. I'm sure the reason, but it works. But, I also need to use the node v12 because of the fields of the EmbedMessage(it uses the `Array.prototype.flat`).

**Comment by ZeroGl1tch** [comment] 2020-03-31 13:04
I found a solution after expermienting a lot. Here it is: https://github.com/amishshah/ytdl-core-discord/issues/6#issuecomment-606612966

**Comment by advaith1** [comment] 2020-05-08 08:14
Should be fixed after the ytdl-core version being used is updated due to https://github.com/fent/node-ytdl-core/commit/f4a9b65

**Comment by Taha-Chaudhry** [comment] 2020-05-12 18:19
> I found a solution after expermienting a lot. Here it is: [#6 (comment)](https://github.com/amishshah/ytdl-core-discord/issues/6#issuecomment-606612966)

i've been trying this, and oddly enough, the problem disappeared, then reappeared a fe days later

**Comment by Taha-Chaudhry** [comment] 2020-05-12 18:20
> Should be fixed after the ytdl-core version being used is updated due to [fent/node-ytdl-core@f4a9b65](https://github.com/fent/node-ytdl-core/commit/f4a9b65)

Didn't fix

**Comment by amishshah** [comment] 2020-09-18 09:52
Duplicate of #6 - if you can still reproduce this issue using `ytdl-core-discord@1.2.2`, please make a new issue.

**Closed by amishshah** 2020-09-18 09:52 UTC
